config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "pages#home"

  resources :pages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
    @pages = Page.all
  end

  def show
    @page = Page.find(params[:id])
  end

  def new
    @page = Page.new
  end

  def create
    @page = Page.new(page_params)

    if @page.save
      redirect_to @page
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @page = Page.find(params[:id])
  end

  def update
    @page = Page.find(params[:id])

    if @page.update(page_params)
      redirect_to @page
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @page = Page.find(params[:id])
    @page.destroy

    redirect_to root_path, status: :see_other
  end


  def home

  end

  private
    def page_params
      params.require(:page).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-full bg-gray-100">
  <head>
    <title><%= content_for(:title) || "Box Portal" %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <!-- Box UI Elements -->
    <link href="https://cdn01.boxcdn.net/platform/elements/14.0.0/en-US/explorer.css" rel="stylesheet" type="text/css"></link>
    <link href="https://cdn01.boxcdn.net/platform/elements/14.0.0/en-US/picker.css" rel="stylesheet" type="text/css"></link>
    <link href="https://cdn01.boxcdn.net/platform/elements/14.0.0/en-US/uploader.css" rel="stylesheet" type="text/css"></link>
    <link href="https://cdn01.boxcdn.net/platform/elements/14.0.0/en-US/openwith.css" rel="stylesheet" type="text/css"></link>
    <link href="https://cdn01.boxcdn.net/platform/elements/14.0.0/en-US/preview.css" rel="stylesheet" type="text/css"></link>
    <link href="https://cdn01.boxcdn.net/platform/elements/14.0.0/en-US/sidebar.css" rel="stylesheet" type="text/css"></link>

    <script src="https://cdn01.boxcdn.net/polyfills/core-js/2.5.3/core.min.js"></script>
    <script src="https://cdn01.boxcdn.net/platform/elements/14.0.0/en-US/explorer.js"></script>
    <script src="https://cdn01.boxcdn.net/platform/elements/14.0.0/en-US/picker.js"></script>
    <script src="https://cdn01.boxcdn.net/platform/elements/14.0.0/en-US/uploader.js"></script>
    <script src="https://cdn01.boxcdn.net/platform/elements/14.0.0/en-US/preview.js"></script>
    <script src="https://cdn01.boxcdn.net/platform/elements/14.0.0/en-US/openwith.js"></script>
    <script src="https://cdn01.boxcdn.net/platform/preview/2.26.0/en-US/preview.js"></script>
    <script src="https://cdn01.boxcdn.net/platform/elements/14.0.0/en-US/sidebar.js"></script>

    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="h-full">
    <div class="min-h-full">
      <nav class="bg-blue-800">
        <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <div class="flex h-16 items-center justify-between">
            <div class="flex items-center">
              <div class="flex-shrink-0">
                <img class="h-8 w-18" src="https://www.nintendo.com/eu/media/images/10_share_images/portals_3/2x1_SuperMarioHub_image1600w.jpg" alt="Headless Box">
              </div>
              <div class="hidden md:block">
                <div class="ml-10 flex items-baseline space-x-4">
                  <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
                  <a href="/" class="rounded-md bg-red-700 px-3 py-2 text-sm font-medium text-white" aria-current="page">My Files</a>
                  <a href="/pages/4" class="rounded-md px-3 py-2 text-sm font-medium text-red-400 hover:bg-red-900 hover:text-white">Upload Receipts</a>
                  <a href="/pages/3" class="rounded-md px-3 py-2 text-sm font-medium text-red-400 hover:bg-red-900 hover:text-white">Work Order</a>
                  <a href="/pages" class="rounded-md px-3 py-2 text-sm font-medium text-red-400 hover:bg-red-900 hover:text-white">Admin</a>
                </div>
              </div>
            </div>
            <div class="hidden md:block">
              <div class="ml-4 flex items-center md:ml-6">
                <button type="button" class="relative rounded-full bg-gray-800 p-1 text-gray-400 hover:text-white focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800">
                  <span class="absolute -inset-1.5"></span>
                  <span class="sr-only">View notifications</span>
                  <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M14.857 17.082a23.848 23.848 0 005.454-1.31A8.967 8.967 0 0118 9.75v-.7V9A6 6 0 006 9v.75a8.967 8.967 0 01-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 01-5.714 0m5.714 0a3 3 0 11-5.714 0" />
                  </svg>
                </button>

                <!-- Profile dropdown -->
                <div class="relative ml-3">
                  <div>
                    <button type="button" class="relative flex max-w-xs items-center rounded-full bg-gray-800 text-sm focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800" id="user-menu-button" aria-expanded="false" aria-haspopup="true">
                      <span class="absolute -inset-1.5"></span>
                      <span class="sr-only">Open user menu</span>
                      <img class="h-8 w-8 rounded-full" src="https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/b6c30fa4-7e9d-405f-8481-305884389e09/deburkc-349685e7-482e-422c-bc42-0780b03666ec.jpg/v1/fill/w_1280,h_1280,q_75,strp/mario_square_by_domthemixture_deburkc-fullview.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9MTI4MCIsInBhdGgiOiJcL2ZcL2I2YzMwZmE0LTdlOWQtNDA1Zi04NDgxLTMwNTg4NDM4OWUwOVwvZGVidXJrYy0zNDk2ODVlNy00ODJlLTQyMmMtYmM0Mi0wNzgwYjAzNjY2ZWMuanBnIiwid2lkdGgiOiI8PTEyODAifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6aW1hZ2Uub3BlcmF0aW9ucyJdfQ.96RPKyMDWJOA4AGutA_1AFp6fGLDwcFV3cyYxMsaT7Q" alt="">
                    </button>
                  </div>

                  <!--
                    Dropdown menu, show/hide based on menu state.

                    Entering: "transition ease-out duration-100"
                      From: "transform opacity-0 scale-95"
                      To: "transform opacity-100 scale-100"
                    Leaving: "transition ease-in duration-75"
                      From: "transform opacity-100 scale-100"
                      To: "transform opacity-0 scale-95"
                  -->
                  
                </div>
              </div>
            </div>
            <div class="-mr-2 flex md:hidden">
              <!-- Mobile menu button -->
              <button type="button" class="relative inline-flex items-center justify-center rounded-md bg-gray-800 p-2 text-gray-400 hover:bg-gray-700 hover:text-white focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800" aria-controls="mobile-menu" aria-expanded="false">
                <span class="absolute -inset-0.5"></span>
                <span class="sr-only">Open main menu</span>
                <!-- Menu open: "hidden", Menu closed: "block" -->
                <svg class="block h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
                </svg>
                <!-- Menu open: "block", Menu closed: "hidden" -->
                <svg class="hidden h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </div>
          </div>
        </div>

        <!-- Mobile menu, show/hide based on menu state. -->
        <div class="md:hidden" id="mobile-menu">
          <div class="space-y-1 px-2 pb-3 pt-2 sm:px-3">
            <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
            <a href="#" class="block rounded-md bg-gray-900 px-3 py-2 text-base font-medium text-white" aria-current="page">My Files</a>
            <a href="#" class="block rounded-md px-3 py-2 text-base font-medium text-gray-300 hover:bg-gray-700 hover:text-white">Upload Receipts</a>
            <a href="#" class="block rounded-md px-3 py-2 text-base font-medium text-gray-300 hover:bg-gray-700 hover:text-white">Work order</a>
            <a href="#" class="block rounded-md px-3 py-2 text-base font-medium text-gray-300 hover:bg-gray-700 hover:text-white">Admin</a>
          </div>
          <div class="border-t border-gray-700 pb-3 pt-4">
            <div class="flex items-center px-5">
              <div class="flex-shrink-0">
                <img class="h-10 w-10 rounded-full" src="https://images.unsplash.com/photo-1657851944486-01c8ac187cd8?q=80&w=3870&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" alt="">
              </div>
              <div class="ml-3">
                <div class="text-base font-medium leading-none text-white">Mario</div>
                <div class="text-sm font-medium leading-none text-gray-400">mario@example.com</div>
              </div>
              <button type="button" class="relative ml-auto flex-shrink-0 rounded-full bg-gray-800 p-1 text-gray-400 hover:text-white focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800">
                <span class="absolute -inset-1.5"></span>
                <span class="sr-only">View notifications</span>
                <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M14.857 17.082a23.848 23.848 0 005.454-1.31A8.967 8.967 0 0118 9.75v-.7V9A6 6 0 006 9v.75a8.967 8.967 0 01-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 01-5.714 0m5.714 0a3 3 0 11-5.714 0" />
                </svg>
              </button>
            </div>
            <div class="mt-3 space-y-1 px-2">
              <a href="#" class="block rounded-md px-3 py-2 text-base font-medium text-gray-400 hover:bg-gray-700 hover:text-white">Your Profile</a>
              <a href="#" class="block rounded-md px-3 py-2 text-base font-medium text-gray-400 hover:bg-gray-700 hover:text-white">Settings</a>
              <a href="#" class="block rounded-md px-3 py-2 text-base font-medium text-gray-400 hover:bg-gray-700 hover:text-white">Sign out</a>
            </div>
          </div>
        </div>
      </nav>

      <%= yield %>
      
  </body>
</html>

app/views/pages/_form.html.erb
<%= form_with model: @page do |form| %>
  <div class="mb-4">
    <%= form.label :title, class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_field :title, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline", placeholder: "Title for this page" %>
  </div>

  <div class="mb-4">
    <%= form.label :description, class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_area :body, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline", placeholder: "Short description for this page"  %>
  </div>

  <label class="block text-gray-700 text-sm font-bold mb-2" for="page_description">Box UI Element on this page</label>
  <div class="inline-block relative w-64 mb-6">
  <select class="block appearance-none w-full bg-white border border-gray-400 hover:border-gray-500 px-4 py-2 pr-8 rounded shadow leading-tight focus:outline-none focus:shadow-outline">
    <option>None</option>
    <option>Content Explorer</option>
    <option>Content Uploader</option>
    <option>Content Preview</option>
  </select>

  <a class="inline-block align-baseline font-bold text-sm text-blue-500 hover:text-blue-800" href="https://developer.box.com/guides/embed/ui-elements/">
      See BUIE Documentation
    </a>
</div>

  <div class="flex items-center justify-between">
    <%= form.button class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
    <a class="inline-block align-baseline font-bold text-sm text-blue-500 hover:text-blue-800" href="#">
        Cancel
      </a>
  </div>

<% end %>

  <p class="text-gray-700 text-base mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8">💻 Developers: Find this page in <code style="background:#ffeff0">app/pages/<%= @page.id %>.html</code>. Add custom code, integrations and extension in that file.</p>
  </main>

app/views/pages/edit.html.erb
<header class="bg-white shadow">
    <div class="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8">
      <h1 class="text-3xl font-bold tracking-tight text-gray-900">Edit Page</h1>
    </div>
</header>
<main>
	<div class="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8">
	  <%= render "form", page: @page %>
	</div>

</div>

app/views/pages/home.html.erb
<header class="bg-white shadow">
    <div class="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8">
      <h1 class="text-3xl font-bold tracking-tight text-gray-900">My Files</h1>
    </div>
</header>
<main>
	<div class="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8">
	  <div class="content-explorer" style="height:620px"></div>
	</div>
</main>

app/views/pages/index.html.erb
<header class="bg-white shadow">
    <div class="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8">
      <h1 class="text-3xl font-bold tracking-tight text-gray-900">Admin Console</h1>
      <h2> Setup pages, users, and settings </h2>
    </div>
</header>
<main>
	<div class="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8">
	  <h1 class="text-3xl font-bold tracking-tight text-gray-900">Pages</h1>

	<div class="flex items-center justify-between">
		<%= link_to "New Page", new_page_path, type: "button", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
  </div>
  <br>

	  <% @pages.each do |page| %>


	    <div class="max-w-sm w-full lg:max-w-full lg:flex">

  <div class="border-r border-b border-l border-t border-gray-400 lg:border-t lg:border-gray-400 bg-white rounded-b lg:rounded-r p-4 flex flex-col justify-between leading-normal">
    <div class="mb-8">
      
      <div class="text-gray-900 font-bold text-xl mb-2">
      	
	        <%= page.title %>
	      </div>
      <p class="text-gray-700 text-base">💻 Developers: Find this page in <code style="background:#ffeff0">app/pages/<%= page.id %>.html</code>. Add custom code, integrations and extension in that file.</p><br>
      <p><a class="text-blue-600" href="<%= page_path(page) %>/edit">Edit page setting</p>
    	</div>
	  </div>
	</div>
	<br>
	  <% end %>


	</div>
	

<div class="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8">
<h1 class="text-3xl font-bold tracking-tight text-gray-900">Users</h1>

<div class="flex items-center">
		<%= link_to "New User", new_page_path, type: "button", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
		<p>This will create new app user and its default folders</p>
  </div>
  <br>

<div class="py-8 px-8 columns-3xs mx-auto bg-white rounded-xl shadow-lg space-y-2 sm:py-4 sm:flex sm:items-center sm:space-y-0 sm:space-x-6">
  <img class="block mx-auto h-24 rounded-full sm:mx-0 sm:shrink-0" src="https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/b6c30fa4-7e9d-405f-8481-305884389e09/deburkc-349685e7-482e-422c-bc42-0780b03666ec.jpg/v1/fill/w_1280,h_1280,q_75,strp/mario_square_by_domthemixture_deburkc-fullview.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9MTI4MCIsInBhdGgiOiJcL2ZcL2I2YzMwZmE0LTdlOWQtNDA1Zi04NDgxLTMwNTg4NDM4OWUwOVwvZGVidXJrYy0zNDk2ODVlNy00ODJlLTQyMmMtYmM0Mi0wNzgwYjAzNjY2ZWMuanBnIiwid2lkdGgiOiI8PTEyODAifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6aW1hZ2Uub3BlcmF0aW9ucyJdfQ.96RPKyMDWJOA4AGutA_1AFp6fGLDwcFV3cyYxMsaT7Q"/>
  <div class="text-center space-y-2 sm:text-left">
    <div class="space-y-0.5">
      <p class="text-lg text-black font-semibold">
        Mario
      </p>
      <p class="text-slate-500 font-medium">
        Chief Plumbing Officer
      </p>
    </div>
    <button class="px-4 py-1 text-sm text-purple-600 font-semibold rounded-full border border-purple-200 hover:text-white hover:bg-purple-600 hover:border-transparent focus:outline-none focus:ring-2 focus:ring-purple-600 focus:ring-offset-2">Edit</button>
  </div>

  <img class="block mx-auto h-24 rounded-full sm:mx-0 sm:shrink-0" src="https://static.wikia.nocookie.net/divided-destiny/images/0/0f/Profile-mk-luigi.7bf2a8f2.aead314d58b63e27.png" />
  <div class="text-center space-y-2 sm:text-left">
    <div class="space-y-0.5">
      <p class="text-lg text-black font-semibold">
        Luigi
      </p>
      <p class="text-slate-500 font-medium">
        Minion
      </p>
    </div>
    <button class="px-4 py-1 text-sm text-purple-600 font-semibold rounded-full border border-purple-200 hover:text-white hover:bg-purple-600 hover:border-transparent focus:outline-none focus:ring-2 focus:ring-purple-600 focus:ring-offset-2">Edit</button>
  </div>

  
</div>

</div>

</div>
</main>

app/views/pages/new.html.erb
<header class="bg-white shadow">
    <div class="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8">
      <h1 class="text-3xl font-bold tracking-tight text-gray-900">New Page</h1>
    </div>
</header>
<main>
  <div class="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8">
    <%= render "form", page: @page %>
  </div>
  </main>
</div>

app/views/pages/show.html.erb
<header class="bg-white shadow">
    <div class="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8">
      <h1 class="text-3xl font-bold tracking-tight text-gray-900"><%= @page.title %></h1>
      <h2> <%= @page.body %></h2>
    </div>
</header>

<h1></h1>

<ul>
  <li><%= link_to "Edit", edit_page_path(@page) %></li>
  <li><%= link_to "Destroy", page_path(@page), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>